version: '3.8'
services:
  api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/chat
      - REDIS_URL=redis://redis:6379
      - SALT_ROUNDS=10
      - COOKIE_DOMAIN=localhost
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=5000
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=ws://localhost:3000
      - NEXT_PUBLIC_APP_NAME=Realtime Chat
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - NEXT_PUBLIC_ENABLE_DEBUG=true
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev -- --hostname 0.0.0.0 --port 5000

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: chat-redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis
    networks:
      - chat-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: chat-mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    networks:
      - chat-network
    restart: unless-stopped
