version: '3.8'

# Development overrides
services:
  api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - JWT_SECRET=dev-jwt-secret-key
      - CORS_ORIGIN=http://localhost:5000
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_ENABLE_DEBUG=true
      - HOSTNAME=0.0.0.0
      - PORT=5000
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev -- --hostname 0.0.0.0 --port 5000
