version: '3.8'

# Development overrides
services:
  api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - JWT_SECRET=dev-jwt-secret-key
      - CORS_ORIGIN=http://localhost:5000
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev:cluster

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_ENABLE_DEBUG=true
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3000
      - HOSTNAME=0.0.0.0
      - PORT=5000
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev -- --hostname 0.0.0.0 --port 5000

  # Redis Commander - Web-based Redis management tool
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: chat-redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis
    networks:
      - chat-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: chat-mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    networks:
      - chat-network
    restart: unless-stopped
