version: '3.8'

services:
  # MongoDB database
  mongo:
    image: mongo:6
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chat
    networks:
      - chat-network

  # Redis (pretty sure i'll use it later)
  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network

  # API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    container_name: chat-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/chat
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=aderbs123
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:5000
    command: ["npm", "run", "start:cluster"]
    depends_on:
      - mongo
      - redis
    networks:
      - chat-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      target: production
    container_name: chat-frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=ws://localhost:3000
      - NEXT_PUBLIC_APP_NAME=Realtime Chat
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - NEXT_PUBLIC_ENABLE_DEBUG=false
    depends_on:
      - api
    networks:
      - chat-network
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:

networks:
  chat-network:
    driver: bridge
